### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by ACReeser** [Tannz0rz/FABRIK#1]
I would like to use and contribute to this library, and a permissive license would be great!

**Comment by Tannz0rz** [comment]
Sure deal, I'll upload one here soon, I haven't contributed to this project for a long time. Hopefully you may make some use of it!

**Comment by Tannz0rz** [comment]
Good luck, I hadn't implemented constraints as I had struggled to figure them out. This individual by the username of "minorlogic" has some amount of experience working with quaternions and had suggested decomposing the quaternion into its respective "swing" and "twist" components. See here: https://stackoverflow.com/questions/32813626/constrain-pitch-yaw-roll
